# eslint configuration
parserOptions:
  ecmaVersion: 2017
  sourceType: module
  ecmaFeatures:
    # support redux shallow copy
    experimentalObjectRestSpread: true
env:
  es6: true
  node: true
  jest: true
plugins:
  - node
extends:
  - 'eslint:recommended'
  - 'plugin:node/recommended'
  - 'airbnb-base'
  - 'plugin:import/errors'
  - 'plugin:import/warnings'
rules:
  indent:
    - error
    - 2
    - SwitchCase: 1
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
    - allowTemplateLiterals: true
  semi:
    - error
    - always
  arrow-parens:
    - error
    - always
  # 以下规则完全信任prettier的输出
  comma-dangle: off
  react/sort-comp: off
  function-paren-newline: off
  object-curly-newline: off
  no-confusing-arrow: off
